services:
  dbstarter:
    image: mariadb:11.6.2
    user: 1000:1000
    env_file: .env
    volumes:
      - ./data/mysql:/var/lib/mysql:delegated
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.27.4-alpine
    volumes:
      - './symfony:/var/www/html:delegated'
      - './var/logs/nginx:/var/log/nginx:cached'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - './docker/nginx/ssl:/etc/nginx/ssl:ro'
    ports:
      - '80:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - './symfony:/var/www/html'
    links:
      - dbstarter
    env_file:
      - .env
    user: 1000:1000

# Uncomment this if you need front and add package.json into symfony folder
  nodejs:
    image: node:23-alpine
    user: 1000:1000
    ports:
      - '3009:3009'
    env_file:
      - .env
    working_dir: '/var/www/html'
    volumes:
      - './symfony:/var/www/html'