services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: prod
    container_name: symfony-php
    environment:
      APP_ENV: prod
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
    depends_on:
      - db
    networks:
      - symfony

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./symfony/public:/var/www/html/public:ro
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: postgres:16
    container_name: symfony-postgres
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - symfony

volumes:
  postgres_data:

networks:
  symfony: